# Generated by Django 4.2.8 on 2024-01-08 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 21, 30, 55, 492335), verbose_name='date published'),
        ),
    ]
